ALTER TYPE "public"."audit_action" ADD VALUE 'STAFF_INVITATION_CANCELLED' BEFORE 'APPOINTMENT_STATUS_UPDATED';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'STAFF_REMOVED' BEFORE 'APPOINTMENT_STATUS_UPDATED';--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'STAFF_ROLE_UPDATED' BEFORE 'APPOINTMENT_STATUS_UPDATED';