export { ErpDemoAnalytics } from "@/features/dashboard/components/pages/analytics";
export { ErpDemoBilling } from "@/features/dashboard/components/pages/billing";
export { ErpDemoCommunity } from "@/features/dashboard/components/pages/community";
export { ErpDemoDashboard } from "@/features/dashboard/components/pages/dashboard";
export { DoctorDashboardPage, DoctorAppointmentsPage, DoctorAppointmentDetailPage, DoctorPatientDirectoryPage, DoctorPatientDetailPage, DoctorOnboardingCenterPage, DoctorAvailabilityPage, DoctorDocumentsPage, DoctorLeavesPage, DoctorConsultationsPage, DoctorConsultationDetailPage, DoctorPracticeLocationsPage, DoctorVerificationVaultPage, DoctorSettingsPage, DoctorProfileManagementPage } from "@/features/dashboard/components/pages/doctor-erp-pages";
export { DoctorsManagementPage } from "@/features/dashboard/components/pages/doctors-management";
export { HospitalProfilePage } from "@/features/dashboard/components/pages/hospital-profile";
export { ErpDemoPatients } from "@/features/dashboard/components/pages/patients";
export { default as PricingPage } from "@/features/dashboard/components/pages/pricing";
export { ErpDemoSettings } from "@/features/dashboard/components/pages/settings";
export { ErpDemoStaff } from "@/features/dashboard/components/pages/staff";
