import { index, integer, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const appointments = pgTable(
  "appointments",
  {
    id: text("id").primaryKey(),
    patientUserId: text("patient_user_id"),
    patientName: text("patient_name").notNull(),
    patientPhone: text("patient_phone"),
    patientAge: integer("patient_age"),
    patientGender: text("patient_gender"),
    patientHeight: text("patient_height"),
    patientWeight: text("patient_weight"),
    doctorId: integer("doctor_id"),
    doctorName: text("doctor_name").notNull(),
    doctorSpecialty: text("doctor_specialty"),
    doctorQualifications: text("doctor_qualifications"),
    hospitalId: integer("hospital_id"),
    hospitalName: text("hospital_name"),
    hospitalAddress: text("hospital_address"),
    departmentName: text("department_name"),
    appointmentDate: timestamp("appointment_date", {
      withTimezone: true,
    }).notNull(),
    appointmentTime: text("appointment_time").notNull(),
    appointmentMode: text("appointment_mode").notNull(),
    reason: text("reason"),
    notes: text("notes"),
    complaintPhotoUrl: text("complaint_photo_url"),
    status: text("status").default("pending_approval").notNull(),
    approvalNotes: text("approval_notes"),
    approvedBy: text("approved_by"),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("appointments_status_idx").on(table.status),
    index("appointments_appointment_date_idx").on(table.appointmentDate),
    index("appointments_patient_user_id_idx").on(table.patientUserId),
  ],
);
